name: Commit Workflow Changes
description: "Commit changes made in a workflow to the repository"
author: Luke Sands <luke.sands@d3code.com.au>

branding:
  icon: "git-commit"
  color: orange

runs:
  using: 'docker'
  image: 'Dockerfile'
