name: Commit Workflow Changes
description: "Commit changes made in a workflow to the repository"
author: Luke Sands <luke.sands@d3code.com.au>

branding:
  icon: "git-commit"
  color: orange

runs:
  using: "composite"
  steps:
    - run: echo "${{ github.action_path }}" >> $GITHUB_PATH
      shell: bash
    - run: |
        git config user.email "$(git log -1 --pretty=format:'%ae')"
        git config user.name "$(git log -1 --pretty=format:'%an')"
      shell: bash
    - run: entrypoint.sh
      shell: bash
